=== LuisBosquez/Encuesta-de-Vulnerabilidad/vulnerabilidad/archivo/sac_cuestionario-config_2_0.dtd
<!--
     DTD para el archivo de cuestionario  del sac

	<!DOCTYPE sac-cuestionario PUBLIC
	          "-//ITESM CCM//DTD SAC 2.0//EN"
	           "sac_cuestionario-config_2_0.dtd">
-->
<!ELEMENT cuestionario 
	(nombre,modo,numeracion,tipoidentificador,titulos,calificar,textos,multiplicador?,
	reglas?,categorias?,preguntas?,acciones?) >

 
<!ELEMENT categorias (catego+) >
<!ELEMENT preguntas (pregunta+) >
<!ELEMENT textos (instrucciones?,final?) >
	<!ELEMENT instrucciones (#PCDATA) >
	<!ELEMENT final (#PCDATA) >

<!-- El nombre del cuestionarios -->
<!ELEMENT nombre (#PCDATA) >
<!-- Modo en que se muestra el cuestionario
	1. Muestra las preguntas por pagina
	2. Muestra una categoria de preguntas por pagina
-->
<!ELEMENT modo (#PCDATA) >
<!-- Modo en que se califica el cuestionario
	1. Califica usando las reglas por categoria
	2. Almacena todo en la bd. Este es el modo predeterminado. 
-->
<!ELEMENT numeracion (#PCDATA) >
<!-- Modo en que se numerara el ejercicio
	1. Sin numeracion, ie ya viene con la pregunta
	2. Numerar en base a la pagina
-->
<!ELEMENT tipoidentificador (#PCDATA) >
<!-- Como maneja el nombre o el id de las preguntas, pensado por que con los valores numericos no se puede usar la validacion. Probar si se puede el che con esto sin problemas
	1. numeros
	2. agrega un prefijo llamado p_
-->
<!ELEMENT calificar (#PCDATA) >

<!-- Representa una categoria o pagina dentro del cuestionario.
	id: id de la categoria empezando en 0
	nombre: nombre identificador de la categoria
	color: Color representativo de la categoria
	title: Titulo de la categoria a usar
	data: Descripcion de la categoria
-->

<!ELEMENT catego (nombre, color?, title?, data? , keyPregunta?)>

	<!ATTLIST catego id CDATA #REQUIRED>

<!--	<!ELEMENT nombre (#PCDATA) >-->
	<!ELEMENT color (#PCDATA) >
	<!ELEMENT title (#PCDATA) >
	<!ELEMENT data (#PCDATA) >
	
	<!ELEMENT keyPregunta (#PCDATA)>
	

<!-- Regla es una serie de expresiones que definen como calificar.-->
<!ELEMENT reglas (regla+)>
	<!ELEMENT regla (#PCDATA) >

<!-- Representa una preguna 
	nombre: Texto de la pregunta
	tipo: Tipo de la pregunta
	valor: Valor para calcular el resultado
	categoria: Categoria a la que pertenece la pregunta
	imagen: imagen si es que la lleva
	subtitulo: Imprime un subtitulo para un bloque de preguntas
	
	acciones- Liga a coleccion de javascriptses
	
	candado: Indica el tipo de proteccion a las preguntas	
		1. De que la respuesta es necesaria
		2. de que la respuesta es necesaria PERO depende de otra respuesta
	candadoDepende: para ser usado con candado
	peso: no sirve
	
--> 
<!ELEMENT pregunta (nombre,imagen?,respuesta*,subtitulo?,tipo,accionesReglas?,valor?,categoria,candado?,candadoDepende?) >
	<!ATTLIST pregunta id CDATA #IMPLIED>
	<!--<!ELEMENT nombre (#PCDATA) >-->
	<!ELEMENT respuesta (#PCDATA) >	
	<!ELEMENT imagen (#PCDATA) >	
	<!ELEMENT tipo (#PCDATA) >	
	<!ELEMENT valor (#PCDATA) >
	<!ELEMENT subtitulo (#PCDATA) >
	<!ELEMENT categoria (#PCDATA) >
	<!ELEMENT candado (#PCDATA) >	
	<!ELEMENT candadoDepende (#PCDATA) >	
	
 
	
<!ELEMENT acciones (accion*) >
	<!ELEMENT accion (#PCDATA) >	
<!--
 El candado define reglas para las preguntas
 1. Que tenga algun valor (Textfield y radio)
 2. Que tenga algun valor (Textfield y radio) y tenga una dependecia en la pagina
-->

<!-- Multiplicador para calcular resultados-->
<!ELEMENT multiplicador (#PCDATA) >
<!-- Imperime el titulo de la categoria-->
<!ELEMENT titulos (#PCDATA) >
<!--

1 - Sin titulo -- DEFAULR
2 - Nombre Categoria 
-->

=== LuisBosquez/Encuesta-de-Vulnerabilidad/vulnerabilidad/archivo/che.xml
<?xml version="1.0"  encoding="UTF-8" ?>
<!DOCTYPE cuestionario SYSTEM "sac_cuestionario-config_2_0.dtd">
<cuestionario> 
<nombre>Cuestionario de Habilidades para el Estudio</nombre>
<modo>1</modo>
<numeracion>1</numeracion>
<tipoidentificador>1</tipoidentificador>
<titulos>1</titulos>
<calificar>1</calificar>
<textos>
	<instrucciones>Conteste las preguntas que se le presentan con Si o No</instrucciones>
</textos>


  
	<reglas>		
		<regla>2'2'6+/7g</regla>	
		<regla>2'7'8+/7g</regla>			
		<regla>2'0'1+/7g</regla>		
		<regla>1'3/7g</regla>					
		<regla>2'4'5+/7g</regla>
	</reglas>	
	  
	<categorias>
		<catego id="0">
			<nombre>A</nombre>
			<color>CC99FF</color>
			<title>Actitud ante el estudio.</title>
			<data>Se refiere a la representación que hace el alumno de la escuela y sus aprendizajes como una estrategia para proyectarse hacia el futuro, en el que intervienen tanto los agentes que lo rodean en la escuela, en la familia y la propia necesidad e interés de aprender, para alcanzar otras metas. </data>			
		</catego>
		<catego id="1">
			<nombre>B</nombre>
			<color>ff6600</color>
			<title>Relación alumno maestro.</title>
			<data>La buena percepción del alumno, respecto a la carga afectiva que da a sus profesores, propicia una motivación inconsciente para la realización de tareas fuera y dentro del aula, así como acercamientos académicos o personales, con sus diferentes profesores. Representa también los esquemas de autoridad que de acuerdo a su propia historia pueden ser aceptados o retados; impidiendo una equilibrada relación que facilite los aprendizajes en el alumno y los procesos de enseñanza en el docente.</data>	
		</catego>
		<catego id="2">
			<nombre>C</nombre>
			<color>99CCFF</color>
			<title>Organización ante el estudio.</title>
			<data>Ninguna actividad que carezca de orden, organización y planeación, puede asegurar el éxito continuo, en éste caso, la organización propicia la formulación de planes de acción que vinculen las cuatro áreas fundamentales para la formación integral de las personas; en la que es importante planear para cada día actividades que satisfagan elementos de índole intelectual, emocional, social y física. Cuando alguna de las cuatro áreas no es atendida o se da mayor peso que a las otras, tarde o temprano surgen desequilibrios en el actuar cotidiano y conflictos en los que en ocasiones se tiene la imposibilidad de percibir y buscar soluciones optimas.</data>	
		</catego>
		<catego id="3">
			<nombre>D</nombre>
			<color>FF6699</color>
			<title>Atención- concentración.</title>
			<data>La atención y la concentración son dos habilidades que se desarrollan durante toda la vida, sin embargo, es en la etapa de escolaridad básica en la que alcanzan su máxima desarrollo a través de las actividades académicas y sobre todo del juego. En la educación superior los estudiantes,  adquieren múltiples intereses minimizando su atención y sobre todo la concentración en las actividades escolares, no así, en otras de tipo social o emocional, por lo que es importante que identifiquen prioridades y pongan en orden sus intereses y necesidades para fortalecer las diferentes habilidades indispensables para el aprendizaje.</data>	
		</catego>
		<catego id="4">
			<nombre>E</nombre>
			<color>FFCC00</color>
			<title>Memoria</title>
			<data>En el sistema escolar el uso de la memoria se privilegia desde tempranas edades sin tomar en cuenta la conveniencia de potenciar más  el tipo de memoria racional que el mecánico, al respecto es importante que el estudiante adquiera habilidades que le permitan aprender estrategias que potencien el uso de la memoria a través del análisis y síntesis de la información para su mejor conservación y aplicación en forma práctica.</data>	
		</catego>
		<catego id="5">
			<nombre>F</nombre>
			<color>FFCC00</color>
			<title>Toma de apuntes.</title>
			<data>La toma de apuntes representa gráficamente el ejercicio de la atención, la concentración y el análisis de la información que el estudiante realiza al estar en clase, además expresa el interés y la motivación hacia el estudio, si estos son consultados posteriormente, en lo que radica la importancia del tomar apuntes claros, precisos y legibles. Los apuntes bien tomados, pueden ser una excelente guía de estudio para los exámenes, además de una fuente consulta para otros cursos de temas similares. La carencia de ellos impide un orden en la habilidad de concretar y analizar los diferentes contenidos de las materias. Se vincula la toma de apuntes con la relación maestro- alumno y la actitud ante el estudio, por la motivación que el estudiante tenga con la materia y el uso de  la habilidad de atención ? concentración y memoria, ya que dicha motivación proviene de planes concretos de vida y carrera.</data>				
		</catego>
		<catego id="6">
			<nombre>G</nombre>
			<color>00FF00</color>
			<title>Lectura de libros de texto.</title>
			<data>Aún cuando existen materias consideradas más de tipo práctico que teórico es importante que el estudiante consulte de manera constante libros de texto que potencien sus aprendizajes, es recomendable que todas las materias definan previamente a los primeros trabajos escolares las diferentes fuentes que el estudiante puede utilizar para la mejor comprensión de los contenidos del área. Los estudiantes que hacen uso de materiales complementarios carecen de la práctica de aprender a aprender por sí mismos, es importante en estos casos, que el profesor motive el uso de diferentes textos para ampliar la visión de la materia.</data>	
		</catego>

		<catego id="7">
			<nombre>H</nombre>
			<color>99CCFF</color>
			<title>Trabajos escritos. </title>
			<data>Generalmente nos referimos por trabajos escritos a la entrega de reportes de lectura o investigación que los estudiantes deberán realizar como base complementaría de sus aprendizajes, sin embargo, en este punto se incluyen los apuntes y notas que permitan optimizar los contenidos de un curso o materia. Se involucran la motivación, el orden de la información, el auto estudio y la  actitud persuasiva de adquirir nuevos aprendizajes a partir de intereses individuales y grupales.</data>	
		</catego>
		<catego id="8">
			<nombre>I</nombre>
			<color>00FF00</color>
			<title>Exámenes.</title>
			<data>Incluye la habilidad para aprender los diferentes contenidos de un curso, así como la percepción de facilidad o dificultad para presentarlos, no todos estudiantes asumen ser buenos en la presentación de exámenes, sobre todo por tratarse de procesos de evaluación en los que no siempre se tiene el habito de prepararse con anticipación.Existen diferentes técnicas de relajación y concentración de la información  que posibilitan aprendizajes más asertivos para aquellos alumnos que entran en  crisis en cada  proceso de evaluación.</data>	
		</catego>
	</categorias>
	
	
	 
	<preguntas>
		<pregunta id="0">
			<nombre>1. Me gusta leer libros de texto porque son muy importantes.</nombre>
			<tipo>1</tipo>
			<valor>1</valor>
			<categoria>0</categoria>
		</pregunta>
		<pregunta id="1">
			<nombre>2. Los maestros comprenden las necesidades de los estudiantes. 	</nombre>
			<tipo>1</tipo>
			<valor>1</valor>
			<categoria>1</categoria>
		</pregunta>
		<pregunta id="2">
			<nombre>3. Con frecuencia me retraso en una materia debido a que tengo que preparar otras.</nombre>
			<tipo>1</tipo>
			<valor>0</valor>
			<categoria>2</categoria>
		</pregunta>
		<pregunta id="3">
			<nombre>4. Prefiero estudiar sin ver o escuchar la T.V., el radio o el CD.</nombre>
			<tipo>1</tipo>
			<valor>1</valor>
			<categoria>3</categoria>
		</pregunta>
		<pregunta id="4">
			<nombre> 5. El recitar para mi mismo es un procedimiento eficaz en el aprendizaje de nombres y lugares. </nombre>
			<tipo>1</tipo>
			<valor>1</valor>
			<categoria>4</categoria>
		</pregunta>
		<pregunta id="5">
			<nombre>6. El utilizar un sistema de signos propios me facilita la toma de apuntes. </nombre>
			<tipo>1</tipo>
			<valor>1</valor>
			<categoria>5</categoria>
		</pregunta>
		<pregunta id="6">
			<nombre>7. Se me dificulta seleccionar los puntos más importantes al leer un tema. </nombre>
			<tipo>1</tipo>
			<valor>0</valor>
			<categoria>6</categoria>
		</pregunta>
		<pregunta id="7">
			<nombre>8. Por lo general dejo para el último momento la preparación de mis trabajos escritos porque tengo dificultades para hacerlos.</nombre>
			<tipo>1</tipo>
			<valor>0</valor>
			<categoria>7</categoria>
		</pregunta>
		<pregunta id="8">
			<nombre>9. Es sencillo prepararme para estudiar exámenes de opción múltiple. </nombre>
			<tipo>1</tipo>
			<valor>1</valor>
			<categoria>8</categoria>
		</pregunta>
		<pregunta id="9">
			<nombre>10. Normalmente me cuesta trabajo concentrarme en mis estudios.</nombre>
			<tipo>1</tipo>
			<valor>0</valor>
			<categoria>0</categoria>
		</pregunta>
		<pregunta id="10">
			<nombre>11. Dudo en pedir ayuda a mis maestros en las materias que se me dificultan. </nombre>
			<tipo>1</tipo>
			<valor>1</valor>
			<categoria>1</categoria>
		</pregunta>
		<pregunta id="11">
			<nombre>12. Los estudiantes destacados son los que han renunciado a las actividades recreativas.</nombre>
			<tipo>1</tipo>
			<valor>0</valor>
			<categoria>2</categoria>
		</pregunta>
		<pregunta id="12">
			<nombre>13. El lugar en donde estudio está lleno de distractores (cuadros, fotos, etc...)</nombre>
			<tipo>1</tipo>
			<valor>0</valor>
			<categoria>3</categoria>
		</pregunta>
		<pregunta id="13">
			<nombre>14. Memorizar mis apuntes poco antes del examen me asegura el éxito. </nombre>
			<tipo>1</tipo>
			<valor>0</valor>
			<categoria>4</categoria>
		</pregunta>
		<pregunta id="14">
			<nombre>15. Por lo general dejo pasar un día o más para revisar mis apuntes tomados en clase. 	</nombre>
			<tipo>1</tipo>
			<valor>0</valor>
			<categoria>5</categoria>
		</pregunta>
		<pregunta id="15">
